name: C++ regression tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build simulator
        run: make -j2
      - name: Run regression tests
        run: make test
